# Do not name any yamls "default", "null", or "basic": these are reserved and will cause issues!
defaults:
  - config_cmbnncs_unet8
  - override pipeline: assembly_on_planck
  - override splits: "1-1"
  - _self_

working_dir        : "cmbNNCS_UNet8_on_Planck/"
fig_model_name     : "cmbNNCS, On Planck"

planck_ds: PlanckAsDataset_${scenario.nside}
trained_wd: "cmbNNCS_UNet8/"
splits.name: 1550
